name: Bot3

on:
  push:
    branches: [ stag ]

env:
  TZ: America/Recife
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
       - uses: rokibhasansagar/slimhub_actions@main

       - name: Reclaiming disk space on / by disabling swap partition
         run: |
               sudo swapoff -av
               sudo rm -f /swapfile
